### ISSUE TITLE
Change 'Checklist' in PULL_REQUEST_TEMPLATE.md

### ISSUE THREAD

**Issue by Sriparno08** [Sriparno08/Start-Contributing#39]
## Category

- [x] Documentation
- [ ] Resource Addition

## Description

We need to change 'Checklist' in PULL_REQUEST_TEMPLATE.md by replacing the current markdown with the suggested markdown.

Current Markdown:

```
## Checklist
<!-- Please go through this checklist and confirm before submission. -->

- [ ] I have read the [Contribution Guidelines](https://github.com/Sriparno08/Start-Contributing/blob/main/CONTRIBUTING.md).
- [ ] My changes generate no new warnings or errors.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have added necessary documentation (if appropriate).
```

Suggested Markdown:

```
## Checklist

<!-- Type 'x' in the square brackets '[ ]' to check the corresponding criteria -->

- [ ] I have gone through the [CONTRIBUTING](https://github.com/Sriparno08/Start-Contributing/blob/main/CONTRIBUTING.md) guide
- [ ] The name of the resource is correctly spelled (if applicable)
- [ ] The link to the resource is working (if applicable)
- [ ] The resource is added in the correct format (if applicable)
```
